
name: Node.js CD with Docker Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Node_CD:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Docker
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t projectx_frontend .
          docker tag projectx_frontend ${{ secrets.DOCKER_USERNAME }}/projectx_frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/projectx_frontend